title: João Rodrigo
email: 97ferreira.flavio+jotaweb@gmail.com
description: >- 
  Portfolio website for João Rodrigo, a portuguese designer.
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  LDKid

permalink: pretty

# Define the creators of the website.
programmer: Flávio Ferreira
designer: João Rodrigo

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/

collections:
  projetos:
    output: true
  trabalhos:
    output: true