title: João Rodrigo
description: >- 
  Portfolio website for João Rodrigo, a portuguese designer.

# Criadores do site, mostrado no Home
programmer: Flávio Ferreira
designer: João Rodrigo Carvalho

# Definições de cores
color_config:
  # Cor pre-definida
  default_hue: 341
  # Saturation e Lightness de todas as cores
  saturation: 80
  lightness: 70
  # A cor que altera o background
  bg_switch: 180

# ============================================================================================================================== #

# Dev stuff, não mexas

# url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  LDKid

# Developer email
email: 97ferreira.flavio+jotaweb@gmail.com

permalink: pretty

include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/

collections:
  projetos:
    output: true
  trabalhos:
    output: true
  informacao:
    output: true